### ISSUE TITLE
[Feature] As an organization admin I want to be able to disable/enable the scheduler

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-mula#13]
As an organization admin I want to be able to disable/enable the scheduler through the UI (rocky)

**Comment by jpbruinsslot** [comment]
The scheduler endpoint `/schedulers` allows a `PATCH` to enable/disable the `populate_queue` field

**Comment by jpbruinsslot** [comment]
CLosing, this issue can be picked up in rocky
